version: '3.9'

services:
  # Flowise service
  flowise:
    image: flowiseai/flowise:latest
    restart: always
    container_name: flowise
    environment:
      - DATABASE_URL=postgres://user:postgres@flowise-db:5433/postgres
      - PORT=3002
      - FLOWISE_USERNAME=memox
      - FLOWISE_PASSWORD=memox123
    ports:
      - "3002:3000"
    depends_on:
      - postgres
    networks:
      - flowise-network
    volumes: 
        - ~/.flowise:/root/.flowise
    entrypoint: /bin/sh -c "sleep 3; flowise start"

  # PostgreSQL service
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: flowise
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - flowise-network

  # Chroma service
  chroma:
    image: chromadb/chroma:latest
    container_name: chroma
    environment:
      - CHROMA_SERVER_HOST=0.0.0.0
      - CHROMA_SERVER_HTTP_PORT=8002
    ports:
      - "8002:8000"
    networks:
      - flowise-network

# Volumes for persistent data
volumes:
  postgres-data:

# Docker network
networks:
  flowise-network:
    driver: bridge